# Stage 1: Build the Vue.js application
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./

RUN npm ci
COPY . .

RUN npm run build

# Stage 2: Serve the built application using Nginx
FROM nginx:1.25-alpine AS runner

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html 
EXPOSE 3000


CMD ["nginx", "-g", "daemon off;"]
